---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: wordle-ai
  labels:
    name: wordle-ai

---
# ConfigMap for environment variables
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordle-ai-config
  namespace: wordle-ai
data:
  LOG_LEVEL: "info"
  VITE_API_BASE_URL: "http://backend-service:8080"

---
# Backend Service (ClusterIP for internal communication)
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: wordle-ai
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: None

---
# Backend Deployment (2 replicas for load balancing)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: wordle-ai
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: wordle-ai-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: wordle-ai-config
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
        - name: logs
          mountPath: /root/logs
      volumes:
      - name: logs
        emptyDir: {}

---
# Frontend Service (LoadBalancer for external access)
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: wordle-ai
  labels:
    app: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 5173
    protocol: TCP
    name: http

---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: wordle-ai
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: wordle-ai-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5173
          name: http
        envFrom:
        - configMapRef:
            name: wordle-ai-config
        livenessProbe:
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

