apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: wordle-ai
  labels:
    app: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 5173
    protocol: TCP
    name: http

